/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cliente;

import static cliente.GUI_Login.objInicio;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import sop_corba.MinisterioImpl;
import sop_corba.usuarioImpl;


/**
 *
 * @author ANDRES
 */
public class GUI_AdminMinisterio extends javax.swing.JFrame {

    //GUI_RegistrarUSer objRegis;
    static GUI_Inicio objInicio;
    static GUI_Login objLogin;
    
   String directorio = System.getProperty("user.dir");
   String separador = System.getProperty("file.separator");
   
   
   //adminInt obj_r=new adminImpl();
    MinisterioImpl obj_r=new MinisterioImpl();
   //Conexion con= new Conexion();
   usuarioImpl usu;
    
    public GUI_AdminMinisterio(GUI_Login objLogin)  {
      
        initComponents();
        this.objLogin=objLogin;
        //obj_r=this.con.getObjetoRemoto();
        this.setLocationRelativeTo(null);
        this.setTitle("Menú Administrador");
        this.setResizable(false);
        this.usu=new usuarioImpl();
       
        fijarEncabezadosTabla();
        //this.obj_r=objRegis.getObjetoRemoto();
        btnModificar.setToolTipText("Selecciona una fila de la tabla de usuarios si deseas modificar la información.");
       
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnatras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Agregar.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 254, -1, 50));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Modificar.png"))); // NOI18N
        btnModificar.setText("Modificar ");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 254, 109, 50));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 254, 102, 50));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Seleccione la opción que desea para el usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 580, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 254, 119, -1));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Login", "Clave"
            }
        ));
        tblUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblUser.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblUser);
        tblUser.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 749, 129));

        btnatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/devolver.png"))); // NOI18N
        btnatras.setText("Atras");
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 254, 114, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoadmini.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

      private void fijarEncabezadosTabla() {
        DefaultTableModel miTableModel = new DefaultTableModel();
        miTableModel.addColumn("Nombre");
        miTableModel.addColumn("Apellido");
        miTableModel.addColumn("Login");
        miTableModel.addColumn("Clave");
        tblUser.setModel(miTableModel);
    }
    public JTable getTabla(){
        return tblUser;
    }
    
    public void registrar(Object[] obj ){
            JTextField txtnombre = new JTextField();
            JTextField txtxedad = new JTextField();
            JTextField txtapellido = new JTextField();
            JTextField txtidentificacion = new JTextField();
            JTextField txtlogin = new JTextField();
            JPasswordField txtPass=new JPasswordField();
            Object[] datos = {"Nombre:\t", txtnombre, "Apellido:\t", txtapellido,"Edad:\t", txtxedad,  "Identificación:\t", txtidentificacion,"Login:\t",txtlogin,"Contraseña",txtPass};
            //int option = JOptionPane.showConfirmDialog(null, datos, "Digite los datos del Ususario:", JOptionPane.CANCEL_OPTION);
            int option=0;
            if (option == JOptionPane.OK_OPTION);
            if (!(txtnombre.getText().equals(""))) {
                if (!(txtxedad.getText().equals(""))) {
                    if (!(txtapellido.getText().equals(""))) {
                       // if (numerico(txtnombre.getText())) {

                            
                                
                                String identificacion = txtnombre.getText();
//                                int id=Integer.parseInt(identificacion);
                                String nombre = txtxedad.getText();
                                String apellido = txtapellido.getText();
                                String edad = txtxedad.getText();  
  //                              int ed=Integer.parseInt(edad);
                                String login=txtlogin.getText();
                                String clave=new String(txtPass.getPassword());
//                                int telf=Integer.parseInt(telefono);
                                
                                
                               JOptionPane.showConfirmDialog(null, "Usuario Agregado Exitosamente", "Informe de Estado", JOptionPane.DEFAULT_OPTION,0,new ImageIcon(directorio+separador+"src"+separador+"iconos"+separador+"muybien.jpg"));
                                Object[] info = {txtnombre.getText(), txtapellido.getText(),txtxedad.getText(),txtidentificacion.getText(),txtlogin.getText(),txtPass.getText()};
                                 DefaultTableModel modelo=(DefaultTableModel)tblUser.getModel();
                                modelo.addRow(obj);
                                
                          

                        /*} else {
                            JOptionPane.showMessageDialog(null, "La Identificación debe ser numerica", "Atención", JOptionPane.ERROR_MESSAGE);
                            txtnombre.setText("");
                        }*/
                    } else {
                        JOptionPane.showMessageDialog(null, "El Apellido debe contener valores", "Atención", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El nombre  debe contener valores", "Atención", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "La Identificación debe contener valores", "Atención", JOptionPane.ERROR_MESSAGE);
            }
    }
    
    public void registrar1(Object[] obj){
          DefaultTableModel modelo=(DefaultTableModel)tblUser.getModel();
          modelo.addRow(obj);
        
    }
  
    
     public boolean numerico(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }
    
   
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
            
            GUI_RegistrarUser objRegUSer;
            
            objRegUSer = new GUI_RegistrarUser(this,usu,"registrar");
            objRegUSer.setTitle("REGISTRAR USUARIO");
            objRegUSer.setVisible(true);
            
            
            if(tblUser.getModel().getRowCount()>0){
                btnModificar.setEnabled(true);
                btnBorrar.setEnabled(true);
            }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
            int fila = tblUser.getSelectedRow();
            
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Para modificar debe seleccionar una fila de la tabla usuarios", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            //int id = (int) tblUser.getValueAt(fila, 0);
            
            GUI_RegistrarUser objRegUSer;
            
            objRegUSer = new GUI_RegistrarUser(this,usu,"editar");
            objRegUSer.setTitle("MODIFICAR USUARIO");
            objRegUSer.setVisible(true);
         
       
        
    

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int fila = tblUser.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Para eliminar debe seleccionar una fila de la tabla de usuarios", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String login =  (String) tblUser.getValueAt(fila, 2);
        
        if (JOptionPane.showConfirmDialog(this, "Esta seguro que desea eliminar el usuario  con login: " + login, "Eliminar", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {

         
                //tienda.eliminarPelicula(id);
                JOptionPane.showMessageDialog(this, "Usuario Eliminado!", "Atencion", JOptionPane.ERROR_MESSAGE);
                //eliminar la fila del jTable
                DefaultTableModel modelo = (DefaultTableModel) tblUser.getModel();
                modelo.removeRow(tblUser.getSelectedRow());
                
                //obj_r=objRegis.getObjetoRemoto();
                obj_r.eliminarUsuario(login);
                
//            tblUser.addRowSelectionInterval(0, 0);
          
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
        objLogin.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnatrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_AdminMinisterio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_AdminMinisterio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_AdminMinisterio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_AdminMinisterio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new GUI_AdminMinisterio(objLogin).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnatras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables
}
